server:
  port: 8888
spring:
  devtools:
    restart:
      additional-paths: src/main/
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: root
    #url: #数据库地址
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Hongkong
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-wait: 100
        max-active: 200
        max-idle: 10
        min-idle: -1
    host: 127.0.0.1 #redis ip
    port: 6379
    password: # redis密码
    timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxx.entity
